spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/study?serverTimezone=UTC&useSSL=false
      username: study
      password: study
      connection-test-query: select 1
      minimum-idle: 2
      maximum-pool-size: 10
      pool-name: SpringBootHikari
      idle-timeout: 10000
      max-lifetime: 100000
      connection-timeout: 10000
      validation-timeout: 10000
  thymeleaf:
    view-names: html/*
    prefix: classpath:/templates/
    suffix: .html
#  config:
#    import: classpath:custom_config.yml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
